name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar Trigger
        run: echo "Trigger pelo ${{github.event_name}}."
