name: 03 - Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: OS
        run: |
          echo "Esse job está rodando em um Ubuntu runner"
          echo "OS: $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: OS
        shell: bash
        run: |
          echo "Esse job está rodando em um Windows runner"
          echo "OS: $RUNNER_OS"
