name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print dados de inicialização"
        if: ${{inputs.debug}}
        run: |
          echo "Triggerado por: ${{github.event_name}}"
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"
      - name: "[debug] Print quando triggerar da main"
        if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
        run: echo "Triggerado pela main"
      - name: Saudação
        run: echo "Aoba mundo!"
